### ISSUE TITLE
Heads-up about yapper package

### ISSUE THREAD

**Issue by songololo** [NiklasRosenstein/docspec#13]
@NiklasRosenstein a heads-up that I've used `docspec-python` for a very simple lightweight parser in [`yapper`](https://github.com/benchmark-urbanism/yapper). I needed something very simple for injecting custom user-defined HTML to play nicely with third-party static site generators. More info in this [blog post](https://blog.benchmarkurbanism.com/technical/yapper/).

Thank you for a useful package. 🙇 👏 

A question: I see that there is talk of Python [deprecating `py2to3`](https://docs.python.org/3/library/2to3.html#module-lib2to3). Any thoughts on the future parsers and if these would be compatible with `docspec-python`?

**Comment by NiklasRosenstein** [comment]
Hey @songololo , 

I'm glad the package is working well for you! Yapper looks quite similar to pydoc-markdown, the project that originally sparked the creation of the `docspec-python` package. If you've seen it before, can you tell what has prompted you from starting a new project?

> A question: I see that there is talk of Python deprecating py2to3. Any thoughts on the future parsers and if these would be compatible with docspec-python?

The API will probably not change as the parser implementation gets updated. But I'm not sure when I'll be able to find the time to re-implement the parser with `libCST`.
