### ISSUE TITLE
Visitor pattern

### ISSUE THREAD

**Issue by tristanlatr** [NiklasRosenstein/docspec#16]
Hi,

I'm working on a modified version of `docspec` and I've implemented the actual visitor pattern. 

The pattern is composed by a super class: `ApiObjectVisitor` and the addition of 2 methods to the ApiObject class: `walk(self, visitor: 'ApiObjectVisitor')` and `walkabout(self, visitor: 'ApiObjectVisitor')`. The design is inspired from docutils [NodeVisitor](https://tristanlatr.github.io/apidocs/docutils/docutils.nodes.NodeVisitor.html). 

I could port those object to this version as well. 

Tell me if you are interested.

**Comment by NiklasRosenstein** [comment]
Hey @tristanlatr , could you elaborate on what makes the existing `visit()` and `filter_visit()` functions insufficient?

**Comment by tristanlatr** [comment]
Hi, 

It’s not insufficient in itself. I could probably hack something that would work with that function.

But the visitor pattern makes the visitor logic much more clear. And it ressembles common visitor present in other packages like ast or docutils. 

Tell me what you think.

**Comment by tristanlatr** [comment]
I will submit a PR with the following generic visitor: https://github.com/twisted/pydoctor/blob/json-docspec/pydoctor/visitor.py

It's "installed" on the ApiObject class with the following code: 
```python
def _get_children(self) -> t.Iterable['ApiObject']:
    if isinstance(self, HasMembers):
      return self.members
    else:
      return ()
  def walk(self, v: visitor.Visitor['ApiObject']) -> None:
    visitor.walk(self, v, get_children=self._get_children)
  def walkabout(self, v: visitor.Visitor['ApiObject']) -> None:
    visitor.walkabout(self, v, get_children=self._get_children)
```

It also ships with `FilterVisitor` and `PrintVisitor` such that the same features are offered with the visitor pattern by default. 

See my code here: https://github.com/twisted/pydoctor/tree/json-docspec/pydoctor/docspec

Note that I've remove all the stuff that was unnecessary for me, but I won't do that with this repo. 

I'll continue to submit patches such that the required modifications that i've done in the fork are also present in this repository, then I'll make `pydoctor` use this repository instead of my fork!

Tell me what you think, Thanks.
