### ISSUE TITLE
How to represent function overloads ?

### ISSUE THREAD

**Issue by tristanlatr** [NiklasRosenstein/docspec#27]
I don't think the current specification supports function overloads.

Function overloads could be represented with a new class `FunctionOverload` and a new attribute `Function.overloads: List['FunctionOverload']`

```python
@dataclasses.dataclass
class FunctionOverload:
    args: List[Argument]
    return_type: Optional[str]
```

Tell me what you think,

**Comment by tristanlatr** [comment]
It could be also done by checking the decorators of the several functions with the same name... But adopting this would make it easier.

**Comment by NiklasRosenstein** [comment]
> It could be also done by checking the decorators of the several functions with the same name...

This :)
