### ISSUE TITLE
Have a `ApiObject.docstring_location`

### ISSUE THREAD

**Issue by tristanlatr** [NiklasRosenstein/docspec#29]
The docstrings do not share the same line number as the object. It would be useful to add another attribute such that we can warns on precice lines while parsing the docstring. 

Let's note that a docstring can be defined by setting the `__doc__` attribute on an object, so that can really be done anywhere in the code.

**Comment by NiklasRosenstein** [comment]
Makes sense. I think I would prefer a `Docstring` object which has a `content` and `location` member. It could be a `str` subclass for the time being to avoid breaking downstream code until a major version bump.

**Comment by tristanlatr** [comment]
So something like ?

```python
@dataclasses.dataclass
class Docstring(str):
    content: str
    location: Location
```

Would the serialization work as expected ?

**Comment by NiklasRosenstein** [comment]
Close. I'm working on it here: https://github.com/NiklasRosenstein/docspec/pull/31

Without a specialized serializer for this class (which could be done as well), the easiest is to declare `content` but make it a property such that it actually returns `self` (see PR above).
