### ISSUE TITLE
Line end

### ISSUE THREAD

**Issue by pawamoy** [NiklasRosenstein/docspec#32]
**Is your feature request related to a problem? Please describe.**
@tristanlatr came to me in https://github.com/mkdocstrings/pytkdocs/issues/64 to tell me about docspec and pydocspec. It seems I had starred docspec some time ago already, but completely forgot about it. It would be nice to join efforts on these projects, and I'm currently testing out docspec and pydocspec to see if they could replace pytkdocs in the Python mkdocstrings handler, so here I am :slightly_smiling_face: .

A thing pytkdocs does is it returns the source code along the structural data. I see that docspec only stores the line start of definitions?

**Describe the solution you'd like**
If docspec stored the line end of definitions as well, we could use it to extract the code block of an object (read the file, split on lines, re-join from `line_start` to `line_end`).

**Comment by NiklasRosenstein** [comment]
Hey @pawamoy ,

I wasn't aware of mkdocstring! There seem to be a lot of variants around for generating Python API documentation in Markdown format. Docspec was spawned by my own incarnation of such a tool called [Pydoc-Markdown](https://github.com/NiklasRosenstein/pydoc-markdown). 😄 I would totally be happy of `docspec` could be the common API documentation description language across these tools.

> If docspec stored the line end of definitions as well, we could use it to extract the code block of an object (read the file, split on lines, re-join from line_start to line_end).

I like the idea. Maybe we could add it to the `Location` class. For backwards compatibility it would need to be an `endlineno: Optional[int] = None`. Would you like to make a contribution for that? It would be great if `docspec-python` could be updated at the same time to support the `Location.endlineno` :)

Cheers,
