### ISSUE TITLE
What's the type of Decoration.args ?

### ISSUE THREAD

**Issue by tristanlatr** [NiklasRosenstein/docspec#45]
Hi, 

`Decoration.args`'s type in the specification is `Optional[List[str]]`, but in the code it's `Optional[str]`. 

Personally, I think it should be `Optional[List[str]]` rather than a simple string. This would make the loader more simple. 

Thanks.

**Comment by NiklasRosenstein** [comment]
👋  It's supposed to be what the specification says, yes. I would prefer to be able to handle this in a backwards compatible way though (like introducing the `Docstring` class), but haven't quite made up my mind about how yet. 😄

**Comment by tristanlatr** [comment]
I don't see how `str` and `List[str]` can be compatible. 
If you really want it to be backwards compatible, we should introduce a new attribute: ` Decoration.arglist`  and deprecate the  `Decoration.args`, in my opinion.

**Comment by tristanlatr** [comment]
Any clue on how to go forward ?

**Comment by NiklasRosenstein** [comment]
Hey @tristanlatr , I like adding `arglist` and deprecating `args`. See #48

**Comment by tristanlatr** [comment]
Thanks !
