### ISSUE TITLE
Dataclasses frozen feature makes it impossible to extend `Docstring` functionalities with sublcasses

### ISSUE THREAD

**Issue by tristanlatr** [NiklasRosenstein/docspec#49]
**Describe the bug**
When trying to extend the `Docstring` class, we get this error: `TypeError: cannot inherit non-frozen dataclass from a frozen one`

**To Reproduce**
```python
class CanTriggerWarnings:
    def warn(self, msg, lineno_offset):
        ...
@dataclasses.dataclass
class Docstring(docspec.Docstring, CanTriggerWarnings):
    ...
```
Load module, see error.

I think `frozen=True` should not be used here. I'll submit a patch.

**Comment by tristanlatr** [comment]
@NiklasRosenstein do you know if that would be possible to merge #50 ?

**Comment by NiklasRosenstein** [comment]
Hey @tristanlatr, sorry for the silence. The idea here was that we can introduce the `Docstring` class in a backwards compatible way and use it in places where there used to be just a string for the docstring. But that didn't work flawlessly either, unfortunately.

https://github.com/NiklasRosenstein/pydoc-markdown/issues/219

In an upcoming major release of docspec, I'll remove the backwards compatibility, `Docstring` will not longer be frozen but also no longer inherit `str`.
