### ISSUE TITLE
"Edit on GitHub" link in the documentation is leading to 404

### ISSUE THREAD

**Issue by tristanlatr** [NiklasRosenstein/docspec#51]
**Describe the bug**
The link on the top right corner of the documentation site is broken (or have never worked)

![Capture d’écran, le 2022-01-06 à 01 50 08](https://user-images.githubusercontent.com/19967168/148341218-893cdf7c-3ed2-4b7d-bc0b-be0368d79150.png)
 
It's looking for the file https://github.com/NiklasRosenstein/docspec/edit/master/docs/specification.md but it does not exists.

**Comment by NiklasRosenstein** [comment]
Thanks for reporting, this is fixed now as I switched to using [Novella](https://pypi.org/project/novella/) for the documentation.
