### ISSUE TITLE
What happened to load_python_modules(files=[]) ?

### ISSUE THREAD

**Issue by tristanlatr** [NiklasRosenstein/docspec#75]
`load_python_modules` used to have a files argument, which was very handy. But it seems it's been removed.

I used this feature in my test suite here: https://github.com/tristanlatr/pydocspec/blob/main/pydocspec/test/__init__.py#L47-L53 to ensure my pydocspec tests cases also passes with docspec generated trees.

**Describe the solution you'd like**
The best would this argument to be supported. 

**Describe alternatives you've considered**
I'm not sure there is currently a workaround, I could simply copy the old function...

**Comment by NiklasRosenstein** [comment]
Hey @tristanlatr , sorry for the long silence. In case this is still relevant to you, I'm adding it back in #81 as per your request!
