### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by malte-klemm-by** [NiklasRosenstein/docspec#8]
Right now, the docspec repository is missing a license file. Even though PyPI states it is licensed under MIT, the file is not in the repo, which prohibits me from using pydoc-markdown in my team as there is a license whitelisting process I have to follow. Could you add a corresponding license file?

**Comment by NiklasRosenstein** [comment]
Hey @malte-klemm-by , thanks flagging. I've just added the license file. Do you need the license file to be included in the package on PyPI?

**Comment by malte-klemm-by** [comment]
No, the license along with repository suffices. Thanks for the quick fix!
